### ISSUE TITLE
Resize fails when first device is not a disk (e. g. is a DVD or floppy)

### ISSUE THREAD

**Issue by EmersonPrado** [sprotheroe/vagrant-disksize#14]
Method [Vagrant::Disksize::Action.identify_disks](https://github.com/sprotheroe/vagrant-disksize/blob/master/lib/vagrant/disksize/actions.rb) returns all storage devices attached to the VM. All methods which deal with disks reference the first device. If this first device is a CD/DVD/floppy, cloning will (thankfully) fail:

```
There was an error while executing `VBoxManage`...
Command: ["clonemedium", "<CD/DVD/floppy path>", "<Same changed to vdi>", "--format", "VDI"]
Stderr: VBoxManage: error: The medium '<CD/DVD/floppy path>' can't be used as the requested device type
```

There should be a filter assuring the method will only return an actual disk.

**Comment by EmersonPrado** [comment]
Opened [PR 15](https://github.com/sprotheroe/vagrant-disksize/pull/15)

**Comment by sprotheroe** [comment]
Merged your PR - thanks!
